version: '3'

name: terrarium

networks:
  terrarium:
    driver: bridge
    name: ${TER_DOCKER_NETWORK:-terrarium}
    external: ${TER_DOCKER_NETWORK_EXTERNAL:-false}

secrets:
  netrc:
    file: $HOME/.netrc

volumes:
  postgres_data:
    name: tr_postgres_data

services:
  postgres:
    image: postgres:11
    container_name: postgres
    networks: [terrarium]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${TR_DB_PASSWORD:-}
      POSTGRES_DB: ${TR_DB_NAME:-cc_terrarium}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  harvester:
    image: cldcvr/terrarium-farm-harvester
    networks: [terrarium]
    secrets:
      - source: netrc
        target: /root/.netrc
    environment:
      # DB config
      TR_DB_TYPE: ${TR_DB_TYPE:-postgres}
      TR_DB_HOST: ${TR_DB_HOST:-postgres}
      TR_DB_USER: ${TR_DB_USER:-}
      TR_DB_PORT: ${TR_DB_PORT:-}
      TR_DB_SSL_MODE: ${TR_DB_SSL_MODE:-}
      TR_DB_PASSWORD: ${TR_DB_PASSWORD:-}
    volumes:
      - .:/app/farm
    depends_on:
      postgres:
        condition: service_healthy
