name: Publish release asset (sql-dump)
on:
  push:
    branches:
      - main

jobs:
  create_artifact:
    name: Create farm harvest sql-dump asset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download latest release asset
        run: |
          make docker-init
          mak pull-release || echo "no release asset found, skipping."
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Generate farm sql dump
        run: |
          make harvest db-dump
        env:
          TR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        
      - name: Create release asset
        run: |
          mkdir release-assets
          cp data/cc_terrarium.psql release-assets/terrarium_farm.psql
          cp data/cc_terrarium_data.sql.gz release-assets/cc_terrarium_data.sql.gz
          ls -la release-assets

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Farm Release"
          files: |
            release-assets/terrarium_farm.psql
            release-assets/cc_terrarium_data.sql.gz
