name: Test Harvest
on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Test Harvest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download latest release asset
        run: |
          make docker-init pull-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Harvest farm sql dump
        run: |
          make harvest db-dump
        env:
          TR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
