name: Publish release asset (sql-dump)
on:
  push:
    branches:
      - main

jobs:
  create_artifact:
    name: Create farm harvest sql-dump asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main 
        uses: actions/checkout@v3
        with:
          path: farm
        
      - name: Checkout terrarium tools
        uses: actions/checkout@v3
        with:
          repository: cldcvr/terrarium
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          path: tools

      - name: Download latest release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p /home/runner/work/terrarium-farm/terrarium-farm/tools/data
          cd /home/runner/work/terrarium-farm/terrarium-farm/farm
          gh release download latest
          cp ./terrarium_farm.psql /home/runner/work/terrarium-farm/terrarium-farm/tools/data/cc_terrarium.psql

      - name: Generate farm sql dump
        run: |
          rm -rf /home/runner/work/terrarium-farm/terrarium-farm/tools/examples/farm
          mkdir /home/runner/work/terrarium-farm/terrarium-farm/tools/examples/farm
          cp -r /home/runner/work/terrarium-farm/terrarium-farm/farm/* /home/runner/work/terrarium-farm/terrarium-farm/tools/examples/farm
          cd /home/runner/work/terrarium-farm/terrarium-farm/tools/
          ls -la ./data
          export TR_DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          make docker-init docker-harvest db-dump 
        
      - name: Create release asset
        run: |
          mkdir /home/runner/work/terrarium-farm/terrarium-farm/release-assets
          cp /home/runner/work/terrarium-farm/terrarium-farm/tools/data/cc_terrarium.psql /home/runner/work/terrarium-farm/terrarium-farm/release-assets/terrarium_farm.psql

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Farm Release"
          files: |
            /home/runner/work/terrarium-farm/terrarium-farm/release-assets/terrarium_farm.psql
      
