name: Test Harvest
on:
  pull_request:
    branches:
      - main

jobs:
  create_artifact:
    name: Test Harvest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main 
        uses: actions/checkout@v3
        with:
          path: farm
        
      - name: Checkout terrarium tools
        uses: actions/checkout@v3
        with:
          repository: cldcvr/terrarium
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          path: tools

      - name: Download latest release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p /home/runner/work/terrarium-farm/terrarium-farm/tools/data
          cd /home/runner/work/terrarium-farm/terrarium-farm/farm
          gh release download latest
          cp ./terrarium_farm.psql /home/runner/work/terrarium-farm/terrarium-farm/tools/data/cc_terrarium.psql

      - name: Harvest farm sql dump
        run: |
          rm -rf /home/runner/work/terrarium-farm/terrarium-farm/tools/examples/farm
          mkdir /home/runner/work/terrarium-farm/terrarium-farm/tools/examples/farm
          cp -r /home/runner/work/terrarium-farm/terrarium-farm/farm/* /home/runner/work/terrarium-farm/terrarium-farm/tools/examples/farm
          cd /home/runner/work/terrarium-farm/terrarium-farm/tools/
          export TR_DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          make docker-init docker-harvest db-dump

          