name: Test Harvest
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  checks:
    name: Test Harvest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download latest release asset # use current latest release data as seed
        run: |
          make docker-init
          make pull-release || echo "no release asset found, skipping."
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Harvest farm sql dump
        run: |
          make harvest db-dump
        env:
          TR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - uses: actions/upload-artifact@v3 # just for reference, upload the dump files as workflow artifacts
        with:
          path: data/*.*sql*
